apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node
  name: node
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-container
          image: manisankardivi/node-test:
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  namespace: node
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32222
  type: NodePort
