apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
  labels:
    app: node
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-container
          image: manisankardivi/new:6.0.104
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node-svc
spec:
  selector:
    app: node
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
