apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy
  labels:
    app: node
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: node-container
          image: manisankardivi/new:6.0.104
